### ISSUE TITLE
ShimmerAndroidInstrumentDriver is using Kotlin Gradle plugin version 1.2.30.

### ISSUE THREAD

**Issue by Kuurusch** [ShimmerEngineering/ShimmerAndroidAPI#11]
Hallo,

I have the problem, that my installed android-Studio is using a higer version of the Kotlin Gradle plugin and it prevents me of building your examples, because it uses Kotlin Gradle plugin version 1.2.30.
Do you know, how I can fix this problem? I've cloned your master-branch.
I tried the API from the master-branch.

**Comment by Kuurusch** [comment]
Ok, so I've changed in the gradle-script of the shimmerAndroidInstrumentDriver the kotlin-version to one I can use  (1.2.51), but now I'm running in the next problem and I'm not shure, if it is because the kotlin-version 1.2.51 don't work with the shimmerInstrumentDriver or if it is an other Problem:
It says: "org.gradle.api.GradleException: Lint found fatal errors while assembling a release target."
Any idea, what could be the problem?

**Comment by JongChern** [comment]
Hi, apologize for the delay, was able to build using
-current master branch using
-ext.kotlin_version = '1.2.51'
-and run the ShimmerBasicExample.

if your problem persist do contact us on
http://shimmersensing.com/support/wearable-sensing-support/

**Comment by Kuurusch** [comment]
Ok, I could compile the 3D-example by commenting out the other examples in the settings.gradle-file. But the problem with the bluetooth-example remains...
