### ISSUE TITLE
Bug in OnTheFlyGyroCal

### ISSUE THREAD

**Issue by Kuurusch** [ShimmerEngineering/ShimmerAndroidAPI#12]
Hey,

I think I've found a bug in the file: OnTheFlyGyroOffsetCal.java

I've tried to compile the 3DOrientation-example and the app crashed when executed on the device. I've found out, that it crashed in the function enableOnTheFlyGyroCal(boolean state) because bufferSize was not defined. The reason is, that it is called in the function enableOnTheFlyGyroCal(boolean state, int bufferSize, double threshold), but there the bufferSize is set after enableOnTheFlyGyroCal(boolean state) is called. I'm using a Shimmer3.

**Comment by JongChern** [comment]
Hi @Kuurusch , I can confirm that the error can be replicated. For the time being until we can push a fix, I would recommend calling the method right before startStreaming is called.
