### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by lucassbroto** [ShimmerEngineering/ShimmerAndroidAPI#18]
Good morning, 

Regarding the Shimmer timestamp, I'm aware that it has it's internal clock to get the logs from, but each time it is turned of, I must sync it againg with its base. 

So can I assume that the timestamp Logged in the measurement is synched to my computer's?

I ask this because i need to put together with another sensor, that uses my computer log.

Thank you.

**Comment by jyong15** [comment]
Hi Lucas,

Thanks for reaching out to us. For any future queries, we recommend submitting them via our website form [here](http://www.shimmersensing.com/support/wearable-sensing-support/) for faster replies.

Regarding your question, just a couple of things to clarify:
1. Are you looking to connect your Shimmer devices with a Windows computer or an Android device?
2. Are you using one of our applications (e.g. Shimmer Capture Android or Consensys PC) or developing your own?


Best Regards,
Joseph

**Comment by lucassbroto** [comment]
Hello, Thank you for your answer!

I am connecting to my computer via Consensys PC, using the free version

**Comment by jyong15** [comment]
Hi,

Apologies for the delay.

Yes, when you connect a Shimmer3 sensor to your computer via the dock, if Consensys is open, it will synchronize the timestamp on the Shimmer3 to the computer's real world clock.

I've attached an excerpt below from our SDLog user manual describing synchronisation with the real-world clock, for your convenience. This is from page 17.

![image](https://user-images.githubusercontent.com/26561407/73668663-2759bd80-46e1-11ea-8e3d-83873e2002f7.png)

You may access the SDLog manual at [this link](http://shimmersensing.com/images/uploads/docs/SDLog_for_Shimmer3_Firmware_User_Manual_rev0.19a.pdf).

You may also refer to our LogAndStream user manual, page 9, for a similar description if you are using the LogAndStream firmware instead. It can be accessed at [this link](http://shimmersensing.com/images/uploads/docs/LogAndStream_for_Shimmer3_Firmware_User_Manual_rev0.11a.pdf).

Hope this helps.


Best,
Joseph

**Comment by jyong15** [comment]
Hi, I will be closing this GitHub issue. Feel free to reach out to us at our website form [here](http://www.shimmersensing.com/support/wearable-sensing-support/) if you have any further questions. 

Thanks.

Best,
Joseph
