### ISSUE TITLE
"Cannot resolve 'math' error" in ShimmerObject.java  

### ISSUE THREAD

**Issue by SachiniEMSPE** [ShimmerEngineering/ShimmerAndroidAPI#19]
I downloaded the API and was able to create a test app (just to familiarize connect, stream, log data to csv functionality) following the basic example. This functioned well without any issue. I used Shimmer3 IMU. But, when I try to study further about the API I found "Cannot resolve 'math' error" in ShimmerObject.java. At the moment I didn't face any build/compile errors. May I know why this is happening or else how to get rid of this? Further, I found that since this file is read-only I could not edit. (I'm using Android Studio 3.5.3)
![Screenshot (90)](https://user-images.githubusercontent.com/48669988/74574315-4c57f700-4f51-11ea-8c4c-adbaa65c7477.png)

**Comment by jyong15** [comment]
Hi,

Thanks for reaching out to us and my apologies for the delay in getting back to you.
We do recommend contacting us through our website support form [here](http://shimmersensing.com/support/wearable-sensing-support/) for quicker replies.

You can resolve that error by adding the apache commons math library to your dependencies, in your app module's _build.gradle_ file. 
For example, please see the line highlighted in yellow below:

![image](https://user-images.githubusercontent.com/26561407/74901549-1b0e7980-53de-11ea-87ef-8fff80c8665e.png)

Note that you might need to do a File -> Invalidate Caches and Restart, then a rebuild of your project after for it to work.

Hope this helps.

Best Regards,
Joseph

**Comment by jyong15** [comment]
Hi, 

I will be closing this issue. For any further enquiries, feel free to contact us through our website support form [here](http://shimmersensing.com/support/wearable-sensing-support/).

Best,
Joseph

**Comment by SachiniEMSPE** [comment]
Yes, It works, Thank you for the support.
