### ISSUE TITLE
URL BinTray FORBIDDEN

### ISSUE THREAD

**Issue by gianluDar** [ShimmerEngineering/ShimmerAndroidAPI#26]
Hi, I'm trying to import the project to Android Studio but I get several errors in the compilation like this for example:

However I noticed that the URL "https://dl.bintray.com/shimmerengineering/Shimmer" always returns a 401 Forbidden also this one: http://dl.bintray.com/shimmerengineering/Shimmer/com/shimmerresearch/managers/bluetoothmanager/ShimmerBluetoothManager/0.9.33beta/ShimmerBluetoothManager-0.9.33beta.pom
always in forbidden.

Even trying to download the JARs I see in the download section I always get the Forbidenn message.

How can I solve this?
Thanks!

**Comment by Aravind-Sundararajan** [comment]
bintray has been sunset as of may 1st, several apps that used it are currently migrating. if you have a cached version of the driver in .gradle, you can include these in your project, otherwise you are waiting for shimmersensing to update the build.gradle or offer build instructions.

**Comment by gianluDar** [comment]
> bintray has been sunset as of may 1st, several apps that used it are currently migrating. if you have a cached version of the driver in .gradle, you can include these in your project, otherwise you are waiting for shimmersensing to update the build.gradle or offer build instructions.

Thanks for the reply, and that's what I figured! Unfortunately, I don't have much time due to delivery of a university research project to wait for the dependency to be migrated. Would there be any way you could send me the jar and everything needed to be able to run the project offline?

Thanks!

**Comment by JongChern** [comment]
As the result of bintray being sunset, we are in the process of migrating to JFrog, please see readme
https://github.com/ShimmerEngineering/ShimmerAndroidAPI/tree/JA-49_test
