### ISSUE TITLE
shimmerBasicExample:mergeExtDexDebug

### ISSUE THREAD

**Issue by shengchen-liu** [ShimmerEngineering/ShimmerAndroidAPI#46]
Hello, 

I am playing with "shimmerBasicExample" and tried to build it from Android Studio.  I encountered this error when I ran it:

```
Execution failed for task ':shimmerBasicExample:mergeExtDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.lang.OutOfMemoryError (no error message)
```

Do you have any suggestions what is wrong?

Thanks,

**Comment by jyong15** [comment]
Hi,

Thank you for reaching out to us.

Just to aid in debugging this issue, could you advise the following please,

- Which branch are you running from?
- What version of Android Studio are you using?

Best Regards,
Joseph

**Comment by jyong15** [comment]
> Hello,
> 
> I am playing with "shimmerBasicExample" and tried to build it from Android Studio. I encountered this error when I ran it:
> 
> ```
> Execution failed for task ':shimmerBasicExample:mergeExtDexDebug'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
>    > java.lang.OutOfMemoryError (no error message)
> ```
> 
> Do you have any suggestions what is wrong?
> 
> Thanks,

Hi,

Thank you for reaching out to us.

Regarding this issue, have you tried setting the IDE and Gradle heap size settings to the maximum available?
This can be found in File -> Settings, by searching for "Memory Settings"

![image](https://user-images.githubusercontent.com/26561407/150291600-47442101-3eb4-4783-af39-2a648fc61b42.png)

Best Regards,
Joseph

**Comment by shengchen-liu** [comment]
> > Hello,
> > I am playing with "shimmerBasicExample" and tried to build it from Android Studio. I encountered this error when I ran it:
> > ```
> > Execution failed for task ':shimmerBasicExample:mergeExtDexDebug'.
> > > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> >    > java.lang.OutOfMemoryError (no error message)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you have any suggestions what is wrong?
> > Thanks,
> 
> Hi,
> 
> Thank you for reaching out to us.
> 
> Regarding this issue, have you tried setting the IDE and Gradle heap size settings to the maximum available? This can be found in File -> Settings, by searching for "Memory Settings"
> 
> ![image](https://user-images.githubusercontent.com/26561407/150291600-47442101-3eb4-4783-af39-2a648fc61b42.png)
> 
> Best Regards, Joseph

Thank you for your reply Joseph.
Your suggestion works!
