### ISSUE TITLE
JFOG ShimmerAPI Page is deactivated

### ISSUE THREAD

**Issue by ducnguyenp** [ShimmerEngineering/ShimmerAndroidAPI#57]
I have implemented the device Shimmer3 through the document: https://github.com/ShimmerEngineering/ShimmerAndroidAPI. And today I built a version for my app and it notified me of a bug, then I clicked on the maven URL: https://shimmersensing.jfrog.io/artifactory/ShimmerAPI and it leave to deactivate page. Now I cannot build my project cause this error. Can you please reactive the maven URL? Thank you very much 
These are some image of the Issue
| a | b |
| - | - |
| <img width="411" alt="Screenshot 2023-07-14 at 09 59 30" src="https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/b31ad53c-0e34-4ce1-b3e6-c2bbdb9904ed"> | ![Screenshot 2023-07-14 at 10 00 25](https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/6a6cac4e-5e0c-4242-92f1-c639531a10e8) |
<img width="1375" alt="MicrosoftTeams-image (2)" src="https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/f38573ef-6a05-4d7e-b0a1-3d4825cff994">

[1_Build.txt](https://github.com/ShimmerEngineering/ShimmerAndroidAPI/files/12075608/1_Build.txt)

**Comment by ShimmerEngineering** [comment]
We've started making the required packages on github now rather than jfrog https://github.com/ShimmerEngineering?tab=packages&repo_name=Shimmer-Java-Android-API . This are the core packages you will require to get the ShimmerAndroidInstrumentDriver and most of the examples working. We have not released a package for ShimmerAndroidInstrumentDriver, we aim to do that and make documentation updates next week.

**Comment by ducnguyenp** [comment]
Sorry for bothering again. I'm having a problem importing by GitHub package.
As your document I have followed, I see that adding dependencies in the file pom.xml is required. But android studio doesn't use Maven as its builder. So I converted it to a gradle format:

 implementation 'com.shimmerresearch:shimmerandroidinstrumentdriver:3.0.74_beta'
 implementation 'com.shimmerresearch:shimmerbluetoothmanager:0.9.47_alpha'
 implementation 'com.shimmerresearch:shimmerdriver:0.9.143_alpha'

and I also delete the maven URL imported

But I keep getting the error that it failed to resolve, can you please help me out? Here is the image of the error, please have a look
<img width="196" alt="Screenshot 2023-07-28 at 11 38 01" src="https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/69299a9c-9757-40b9-9795-82eb03a9728f">
![Screenshot 2023-07-28 at 11 37 42](https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/337248cb-36b0-444f-b396-b96d024f98ae)
![Screenshot 2023-07-28 at 11 36 54](https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/a8b05cee-02dc-4ff0-b6cf-b39be4ae1d77)

**Comment by ShimmerEngineering** [comment]
hi, we've updated the master branch now to make sure github packages is included as a repository. see
https://github.com/ShimmerEngineering/ShimmerAndroidAPI/blob/master/ShimmerAndroidInstrumentDriver/build.gradle

hope that helps.

**Comment by ducnguyenp** [comment]
Thanks that worked
