### ISSUE TITLE
Package is missing

### ISSUE THREAD

**Issue by ducnguyenp** [ShimmerEngineering/ShimmerAndroidAPI#61]
When I build my app, it returns a shimmer error. When I check the package, there is only one instead of 3. Have the packages is delete permanently or just temporarily?. Please have a check if it is an error. Thanks 

<img width="1359" alt="image" src="https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/02d32967-c8f2-44be-8c82-ce5f611e5f0c">

**Comment by ShimmerEngineering** [comment]
apologies for the inconvenience. we are looking at the problem now.

**Comment by ShimmerEngineering** [comment]
hi can you give this a try now.

**Comment by Ondrashh** [comment]
I am able to download those other two necessary packages now. Thank you

**Comment by ShimmerEngineering** [comment]
closing issue, thanks for the feedback, and apologies for the inconvenience.
