### ISSUE TITLE
Shimmer not always return 250 value/s event has set the sampling rate to 250

### ISSUE THREAD

**Issue by ducnguyenp** [ShimmerEngineering/ShimmerAndroidAPI#64]
Hi, I have a problem like this, I have set the shimmer device sampling rate to 250, but when I receive the data, it does not always return 250/s. Can you verify this is Shimmer 3 device behavior, or am I misconfiguring the shimmer device?

Thanks

Here is the image I took to see the data each second.

<img width="345" alt="image" src="https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/cdf3ae32-8aae-4074-94f4-a76715cf0bf4">

**Comment by JongChern** [comment]
Sorry i don't quite understand how you are calculating this, are you counting the number of object clusters are being created/produced within a second?

**Comment by ducnguyenp** [comment]
> Sorry i don't quite understand how you are calculating this, are you counting the number of object clusters are being created/produced within a second?

Yes, so I tested to see how many values return each second based on the Timestamp value of the shimmer device. And I noted that it does not always return the exact Sampling rate that I configured. So I just want to know if it is the shimmer behavior or if it is my bad for the configuration that I set.

**Comment by JongChern** [comment]
I see it might be contributed to packet loss. So packet loss will reduce the number of packets you receive. That said some of the values from your screenshot look really low. I would recommend writing the sensor data/object clusters to a file for further examination.

**Comment by ducnguyenp** [comment]
<img width="857" alt="image" src="https://github.com/ShimmerEngineering/ShimmerAndroidAPI/assets/96402550/f6d5e83a-1502-47fd-bdab-41a57f36d743">

This is the configuration I have set, I have followed this with your example shimmer application. Please have a look if it is missing or incorrect.
Thank you very much
