### ISSUE TITLE
Problems with latest Android Studio and Java 17

### ISSUE THREAD

**Issue by sbattaglino** [ShimmerEngineering/ShimmerAndroidAPI#69]
This version requires sourceCompatibility,  targetCompatibility and jvmToolchain to 11
Latest versions of Android and Gradle uses Java 17.
But the Shimmer library will not work.

I have fixed that by changing this in the `app/build.gradle` file

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}
kotlin {
    jvmToolchain(11)
}
```

And I have added the following libraries. Java 11 does not contain required libraries by Shimmer (available in Java 17). 
They need to be added.

```
implementation 'org.apache.commons:commons-math:2.2'
implementation 'javax.vecmath:vecmath:1.5.2'
implementation 'org.apache.commons:commons-lang3:3.13.0'
```

**Comment by ShimmerEngineering** [comment]
hi, apologies for the delay, we've added a page showing how to set the jdk. We hope that helps.

https://github.com/ShimmerEngineering/ShimmerAndroidAPI/wiki/Android-Studio-Setup-(2023.1.1-Patch-2)
