### ISSUE TITLE
Current version doesn't work

### ISSUE THREAD

**Issue by moneypuch** [ShimmerEngineering/ShimmerAndroidAPI#80]
Hello, I'm trying to use your current version 0.86 and it doesn't work, I'm using android studio 2024, could you update a good guide and provide a working version ?

**Comment by JongChern** [comment]
thanks, for getting in touch, it would help to get further info on this. e.g. error, what project you are trying to use etc.

**Comment by JongChern** [comment]
![image](https://github.com/user-attachments/assets/55718931-1b06-44a4-bcd3-d062230f76d2)
working on Android 2024 on my end

**Comment by moneypuch** [comment]
![IMG-20241022-WA0004](https://github.com/user-attachments/assets/394e122a-2f28-40d9-af86-8fd1c8c0cbe0)
![IMG-20241023-WA0023](https://github.com/user-attachments/assets/ac780d34-cbbf-4bd3-ad00-7c3dc173ea5d)
I've got several problems with dependencies I think, could you please share a video from zero , which version of gradle are you using?

**Comment by JongChern** [comment]
looks like you are missing androidx, please see the following:-

https://github.com/ShimmerEngineering/ShimmerAndroidAPI/wiki/Upgrading-to-AndroidX

**Comment by moneypuch** [comment]
> looks like you are missing androidx, please see the following:-
> 
> https://github.com/ShimmerEngineering/ShimmerAndroidAPI/wiki/Upgrading-to-AndroidX

Ok, did you look the other photo? I downloaded the 0.86 version, I tried to follow the Quick start guide and It doesn't work, I changed the gradle version to 11 like it showed in android 2023 fix Page , but I got several problems when I tried to run any example. Why there are missing a lot of things to run this project? I asked other people to try and they have the same result. Coul you help me?

**Comment by JongChern** [comment]
best for us to make sure you can run the examples first.

**Comment by moneypuch** [comment]
I don't understand, what I have to do?

**Comment by JongChern** [comment]
you showed an error with android x, lets fix that first and then move on to the next problem with the examples. to do that you will need to add the following:-
![image](https://github.com/user-attachments/assets/3bbaaa61-c2a1-489b-89eb-82964f531c9c) to your gradle.properties file

**Comment by moneypuch** [comment]
![Screenshot (316)](https://github.com/user-attachments/assets/af3f3126-f558-4e3c-aecb-90388c433700)
![Screenshot (317)](https://github.com/user-attachments/assets/d55d23c4-2c28-47b6-ab8e-4eca523d1c60)
![Screenshot (318)](https://github.com/user-attachments/assets/0bdb8777-8952-4d41-8ac3-e89576d3b637)

I tried a lot of time and I found a lot of different errors. How is possible? Could you please make a video or something from scratch, showing every step? Thank you

**Comment by JongChern** [comment]
thank you for your patience. we have added the following https://github.com/ShimmerEngineering/ShimmerAndroidAPI/wiki/Guide-for-Android-Studio-2024.2.1-Patch-2
we hope that helps.
